server:
  port: 8082
spring:
  cloud:
    gateway:
      routes:
        - id: posts_service
          uri: http://localhost:8080/
          predicates:
          - Path=/posts/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE